# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from imu/IMU_Data.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class IMU_Data(genpy.Message):
  _md5sum = "7d45cb493d33cb1dd3f277b4b672e446"
  _type = "imu/IMU_Data"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32[3] accel
float32[3] mag
float32[3] angrate
float32[4] quat
float64 time
"""
  __slots__ = ['accel','mag','angrate','quat','time']
  _slot_types = ['float32[3]','float32[3]','float32[3]','float32[4]','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       accel,mag,angrate,quat,time

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(IMU_Data, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.accel is None:
        self.accel = [0.,0.,0.]
      if self.mag is None:
        self.mag = [0.,0.,0.]
      if self.angrate is None:
        self.angrate = [0.,0.,0.]
      if self.quat is None:
        self.quat = [0.,0.,0.,0.]
      if self.time is None:
        self.time = 0.
    else:
      self.accel = [0.,0.,0.]
      self.mag = [0.,0.,0.]
      self.angrate = [0.,0.,0.]
      self.quat = [0.,0.,0.,0.]
      self.time = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_struct_3f.pack(*self.accel))
      buff.write(_struct_3f.pack(*self.mag))
      buff.write(_struct_3f.pack(*self.angrate))
      buff.write(_struct_4f.pack(*self.quat))
      buff.write(_struct_d.pack(self.time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 12
      self.accel = _struct_3f.unpack(str[start:end])
      start = end
      end += 12
      self.mag = _struct_3f.unpack(str[start:end])
      start = end
      end += 12
      self.angrate = _struct_3f.unpack(str[start:end])
      start = end
      end += 16
      self.quat = _struct_4f.unpack(str[start:end])
      start = end
      end += 8
      (self.time,) = _struct_d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(self.accel.tostring())
      buff.write(self.mag.tostring())
      buff.write(self.angrate.tostring())
      buff.write(self.quat.tostring())
      buff.write(_struct_d.pack(self.time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 12
      self.accel = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      start = end
      end += 12
      self.mag = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      start = end
      end += 12
      self.angrate = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      start = end
      end += 16
      self.quat = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=4)
      start = end
      end += 8
      (self.time,) = _struct_d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_4f = struct.Struct("<4f")
_struct_3f = struct.Struct("<3f")
_struct_d = struct.Struct("<d")
