set(_CATKIN_CURRENT_PACKAGE "imu")
set(imu_VERSION "0.0.0")
set(imu_MAINTAINER "odroid <odroid@todo.todo>")
set(imu_PACKAGE_FORMAT "1")
set(imu_BUILD_DEPENDS "roscpp" "rospy" "serial" "std_msgs" "message_generation")
set(imu_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "serial" "std_msgs" "message_runtime")
set(imu_BUILDTOOL_DEPENDS "catkin")
set(imu_BUILDTOOL_EXPORT_DEPENDS )
set(imu_EXEC_DEPENDS "roscpp" "rospy" "serial" "std_msgs" "message_runtime")
set(imu_RUN_DEPENDS "roscpp" "rospy" "serial" "std_msgs" "message_runtime")
set(imu_TEST_DEPENDS )
set(imu_DOC_DEPENDS )
set(imu_DEPRECATED "")