// Generated by gencpp from file imu_int/ImuIntCommandRequest.msg
// DO NOT EDIT!


#ifndef IMU_INT_MESSAGE_IMUINTCOMMANDREQUEST_H
#define IMU_INT_MESSAGE_IMUINTCOMMANDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace imu_int
{
template <class ContainerAllocator>
struct ImuIntCommandRequest_
{
  typedef ImuIntCommandRequest_<ContainerAllocator> Type;

  ImuIntCommandRequest_()
    : reset(0)  {
    }
  ImuIntCommandRequest_(const ContainerAllocator& _alloc)
    : reset(0)  {
  (void)_alloc;
    }



   typedef uint8_t _reset_type;
  _reset_type reset;




  typedef boost::shared_ptr< ::imu_int::ImuIntCommandRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imu_int::ImuIntCommandRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ImuIntCommandRequest_

typedef ::imu_int::ImuIntCommandRequest_<std::allocator<void> > ImuIntCommandRequest;

typedef boost::shared_ptr< ::imu_int::ImuIntCommandRequest > ImuIntCommandRequestPtr;
typedef boost::shared_ptr< ::imu_int::ImuIntCommandRequest const> ImuIntCommandRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::imu_int::ImuIntCommandRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::imu_int::ImuIntCommandRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace imu_int

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'imu_int': ['/home/auvic/catkin_ws/src/imu_int/msg', '/home/auvic/catkin_ws/src/imu_int/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::imu_int::ImuIntCommandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_int::ImuIntCommandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_int::ImuIntCommandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_int::ImuIntCommandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_int::ImuIntCommandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_int::ImuIntCommandRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::imu_int::ImuIntCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7a9e14ea4bf436d69f6772a63b82c533";
  }

  static const char* value(const ::imu_int::ImuIntCommandRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7a9e14ea4bf436d6ULL;
  static const uint64_t static_value2 = 0x9f6772a63b82c533ULL;
};

template<class ContainerAllocator>
struct DataType< ::imu_int::ImuIntCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imu_int/ImuIntCommandRequest";
  }

  static const char* value(const ::imu_int::ImuIntCommandRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::imu_int::ImuIntCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 reset\n\
";
  }

  static const char* value(const ::imu_int::ImuIntCommandRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::imu_int::ImuIntCommandRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.reset);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImuIntCommandRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imu_int::ImuIntCommandRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::imu_int::ImuIntCommandRequest_<ContainerAllocator>& v)
  {
    s << indent << "reset: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reset);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMU_INT_MESSAGE_IMUINTCOMMANDREQUEST_H
