// Generated by gencpp from file imu_int/ImuIntCommand.msg
// DO NOT EDIT!


#ifndef IMU_INT_MESSAGE_IMUINTCOMMAND_H
#define IMU_INT_MESSAGE_IMUINTCOMMAND_H

#include <ros/service_traits.h>


#include <imu_int/ImuIntCommandRequest.h>
#include <imu_int/ImuIntCommandResponse.h>


namespace imu_int
{

struct ImuIntCommand
{

typedef ImuIntCommandRequest Request;
typedef ImuIntCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ImuIntCommand
} // namespace imu_int


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::imu_int::ImuIntCommand > {
  static const char* value()
  {
    return "ca8650a271a97fe0aa482cb731f73128";
  }

  static const char* value(const ::imu_int::ImuIntCommand&) { return value(); }
};

template<>
struct DataType< ::imu_int::ImuIntCommand > {
  static const char* value()
  {
    return "imu_int/ImuIntCommand";
  }

  static const char* value(const ::imu_int::ImuIntCommand&) { return value(); }
};


// service_traits::MD5Sum< ::imu_int::ImuIntCommandRequest> should match 
// service_traits::MD5Sum< ::imu_int::ImuIntCommand > 
template<>
struct MD5Sum< ::imu_int::ImuIntCommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::imu_int::ImuIntCommand >::value();
  }
  static const char* value(const ::imu_int::ImuIntCommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::imu_int::ImuIntCommandRequest> should match 
// service_traits::DataType< ::imu_int::ImuIntCommand > 
template<>
struct DataType< ::imu_int::ImuIntCommandRequest>
{
  static const char* value()
  {
    return DataType< ::imu_int::ImuIntCommand >::value();
  }
  static const char* value(const ::imu_int::ImuIntCommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::imu_int::ImuIntCommandResponse> should match 
// service_traits::MD5Sum< ::imu_int::ImuIntCommand > 
template<>
struct MD5Sum< ::imu_int::ImuIntCommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::imu_int::ImuIntCommand >::value();
  }
  static const char* value(const ::imu_int::ImuIntCommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::imu_int::ImuIntCommandResponse> should match 
// service_traits::DataType< ::imu_int::ImuIntCommand > 
template<>
struct DataType< ::imu_int::ImuIntCommandResponse>
{
  static const char* value()
  {
    return DataType< ::imu_int::ImuIntCommand >::value();
  }
  static const char* value(const ::imu_int::ImuIntCommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IMU_INT_MESSAGE_IMUINTCOMMAND_H
